// UI strings. To add a language: copy the "en" block, translate it and add the
// language to LANGS in i18n.js.

export const STRINGS = {
  es: {
    "connect.demo": "Probar con datos de ejemplo (sin guardar nada)", "demo.title": "Modo demo", "demo.text": "Los cambios no se guardan.", "demo.connect": "Usar mi bóveda",
    "err.offlineWeb": "Sin conexión con tu bóveda. Revisa tu conexión a internet o el permiso de la carpeta.", "err.backend": "No se puede abrir tu bóveda",
    "storage.github": "Repositorio de GitHub", "storage.folder": "Carpeta de este ordenador", "storage.disconnect": "Desconectar",
    "storage.githubHelp": "Cada cambio es un commit en tu repositorio privado: tienes el historial completo y puedes abrirlo desde cualquier dispositivo. El token solo se guarda en este navegador.",
    "storage.folderHelp": "Tus archivos no salen de este ordenador. Pon la carpeta en OneDrive/Dropbox/iCloud si quieres tenerla sincronizada.",
    "storage.disconnectConfirm": "Panel olvidará esta bóveda en este navegador (tus archivos no se borran). ¿Continuar?",
    "cal.webOnly": "En la versión web no se pueden leer calendarios (los navegadores lo impiden por seguridad). Usa la versión de escritorio para ver tus reuniones de Outlook, Google o iCloud automáticamente.",
    "upd.web": "La versión web se actualiza sola: siempre tienes la última.",
    "connect.lead": "Tareas, reuniones, proyectos y notas en archivos Markdown que son solo tuyos. ¿Dónde quieres guardarlos?",
    "connect.recommended": "Recomendado", "connect.folderTitle": "Una carpeta de este ordenador",
    "connect.folderText": "Tus datos no salen de tu equipo. Ideal para el trabajo. Puedes ponerla en OneDrive o Dropbox para sincronizarla.",
    "connect.folderUnsupported": "Tu navegador no permite abrir carpetas. Usa Chrome, Edge o Brave en el ordenador, o elige GitHub / la versión de escritorio.",
    "connect.folderBtn": "Elegir carpeta", "connect.ghTitle": "Un repositorio privado de GitHub",
    "connect.ghText": "Sincronizado en todos tus dispositivos, también el móvil, con historial de cada cambio. Gratis.",
    "connect.ghBtn": "Conectar GitHub", "connect.gh1": "Crea un repositorio privado vacío.", "connect.gh1link": "Crear repositorio →",
    "connect.gh2": "Crea un token con permiso «Contents: Read and write» solo para ese repositorio.", "connect.gh2link": "Crear token →",
    "connect.gh3": "Pega aquí el repositorio y el token.", "connect.repo": "Repositorio", "connect.token": "Token",
    "connect.tokenHint": "Se guarda solo en este navegador y solo se envía a api.github.com.",
    "connect.ghConnect": "Conectar", "connect.repoInvalid": "Escribe el repositorio como usuario/nombre", "connect.tokenMissing": "Falta el token",
    "connect.desktopTitle": "Versión de escritorio", "connect.desktopText": "Para Firefox o Safari, sin conexión, o para ver automáticamente tu calendario de Outlook. Descarga, descomprime y doble clic.",
    "connect.privacy": "Panel no tiene servidores ni cuentas: la app se ejecuta en tu navegador y tus datos van directamente a tu carpeta o a tu GitHub.",
    "connect.about": "Código abierto · GitHub", "connect.reopen": "Abrir «{name}»",
    "connect.reopenText": "Por seguridad, el navegador pide permiso cada cierto tiempo para volver a abrir tu carpeta.", "connect.other": "Usar otra bóveda",
    "event.allDay": "Todo el día", "event.takeNotes": "Crear las notas de esta reunión", "event.hint": "De tu calendario · clic para tomar notas",
    "settings.tab.general": "General", "settings.tab.calendar": "Calendario", "settings.tab.vault": "Bóveda", "settings.tab.updates": "Actualizaciones",
    "cal.settingsHelp": "Las reuniones de tu calendario aparecen solas en Hoy, Semana y Calendario. Un clic en una crea su nota (con título, hora y asistentes) y la coloca en el plan del día. Panel solo lee el calendario, nunca lo modifica.",
    "cal.outlook": "Outlook de escritorio", "cal.outlookHint": "lee el calendario del Outlook clásico instalado en este ordenador (Windows).",
    "cal.outlookOnlyWin": "solo disponible en Windows con el Outlook clásico.",
    "cal.outlookAttendees": "Leer también los asistentes (Outlook puede pedir permiso la primera vez)",
    "cal.icsLabel": "Calendarios .ics (uno por línea)", "cal.icsHint": "Enlace ICS de Outlook web (Configuración → Calendario → Calendarios compartidos → Publicar), Google Calendar (Dirección secreta en formato iCal), iCloud… o la ruta de un archivo .ics.",
    "cal.saveTest": "Guardar y probar", "cal.testing": "Leyendo el calendario…", "cal.testResult_one": "Conectado: 1 evento en las próximas 2 semanas", "cal.testResult_other": "Conectado: {n} eventos en las próximas 2 semanas",
    "vault.folder": "Carpeta de la bóveda", "vault.folderHint": "Puedes ponerla en OneDrive, Dropbox, iCloud o Syncthing para tenerla sincronizada entre ordenadores. Si la carpeta nueva está vacía, Panel te ofrecerá crearla o migrarla.",
    "vault.change": "Usar esta carpeta", "vault.changeConfirm": "Panel se reiniciará usando la carpeta «{path}». Tu bóveda actual no se mueve ni se borra (muévela tú a esa carpeta antes si quieres conservarla allí). ¿Continuar?",
    "vault.changeOk": "Cambiar y reiniciar", "vault.restarting": "Reiniciando Panel con la nueva carpeta…",
    "vault.backupTitle": "Copias de seguridad y exportación", "vault.backupHelp": "Exporta toda tu bóveda en un .zip (para llevarla a otro ordenador o guardarla). Antes de cada actualización Panel hace una copia automática en la carpeta backups/.",
    "vault.export": "Exportar bóveda (.zip)", "vault.backupNow": "Hacer copia ahora", "vault.backupDone": "Copia guardada en {path}",
    "vault.syncHelp": "Para cambiar de ordenador: instala Panel, copia tu carpeta de bóveda (o descomprime el .zip) y elige esa carpeta aquí.",
    "upd.checking": "Buscando actualizaciones…", "upd.auto": "Buscar actualizaciones al arrancar", "upd.help": "Las actualizaciones se descargan de github.com/{repo}. Tus datos nunca se tocan y se hace una copia de la bóveda antes de actualizar.",
    "upd.available": "Nueva versión disponible: {v}", "upd.install": "Actualizar a {v}", "upd.installShort": "Actualizar", "upd.upToDate": "Tienes la última versión",
    "upd.title": "Actualizar Panel", "upd.confirm": "Se descargará la versión {v}, se hará una copia de tu bóveda en backups/ y Panel se reiniciará solo. ¿Actualizar ahora?",
    "upd.installing": "Descargando e instalando la actualización…", "upd.restarting": "Reiniciando Panel…", "upd.banner": "Actualizar a {v}", "upd.check": "Buscar actualizaciones",
    "common.open": "Abrir", "cal.plan": "Plan del día",
    "meeting.onlyDays": "Las reuniones solo se pueden colocar en un día", "meeting.rescheduled": "Reunión movida a {date}",
    "meeting.unplace": "Quitar del plan del día", "meeting.unplaceHint": "sigue existiendo",
    "meeting.dragHint": "Arrastra la reunión entre las tareas para ordenar tu día",
    "project.closedLink_one": "1 terminado o en pausa →", "project.closedLink_other": "{n} terminados o en pausa →",
    "tpl.title": "Plantillas", "tpl.label": "Plantilla", "tpl.default": "Por defecto", "tpl.builtin": "integrada", "tpl.edit": "Editar plantillas",
    "tpl.new": "nueva", "tpl.new.meeting": "Nueva plantilla de reunión", "tpl.new.note": "Nueva plantilla de nota", "tpl.create": "Crear plantilla",
    "tpl.namePh": "Ej. Retro, 1:1, Entrevista…", "tpl.kind.meeting": "Reuniones", "tpl.kind.note": "Notas",
    "tpl.editing": "Plantilla · {name}",
    "tpl.help": "Las plantillas son archivos .md en la carpeta templates/ de tu bóveda. La que se llama meeting.md (o note.md) es la de por defecto; crea más y elige cuál usar al crear una reunión o nota.",
    "tpl.placeholders": "Variables disponibles: {{title}} · {{date}} · {{time}} · {{project}} · {{attendees}} · {{today}} · {{weekday}} · {{dateLong}}",
    "nav.today": "Hoy", "nav.inbox": "Bandeja", "nav.week": "Semana", "nav.calendar": "Calendario",
    "nav.meetings": "Reuniones", "nav.notes": "Tablón", "nav.projects": "Proyectos", "nav.search": "Buscar",

    "common.cancel": "Cancelar", "common.close": "Cerrar", "common.color": "Color", "common.confirm": "Confirmar",
    "common.copied": "Copiado", "common.date": "Fecha", "common.delete": "Eliminar", "common.description": "Descripción",
    "common.edit": "Editar", "common.more": "Más opciones", "common.name": "Nombre", "common.noResults": "Sin resultados",
    "common.openFile": "Abrir el archivo .md", "common.project": "Proyecto", "common.save": "Guardar", "common.seeAll": "Ver todo",
    "common.tags": "Etiquetas", "common.tasks": "Tareas", "common.time": "Hora", "common.title": "Título", "common.undo": "Deshacer",

    "date.today": "Hoy", "date.tomorrow": "Mañana", "date.yesterday": "Ayer", "date.nextWeek": "La semana que viene",
    "time.now": "ahora mismo",

    "greet.morning": "Buenos días", "greet.afternoon": "Buenas tardes", "greet.evening": "Buenas noches", "greet.night": "Buenas noches",

    "today.progress": "{done} de {total} tareas hechas", "today.nothing": "Nada planificado para hoy (todavía)",
    "today.overdue": "Atrasadas", "today.bringAll": "Pasar todas a hoy", "today.broughtAll_one": "1 tarea movida a hoy",
    "today.broughtAll_other": "{n} tareas movidas a hoy", "today.tasks": "Plan de hoy", "today.addPh": "¿Qué tienes que hacer hoy?",
    "today.meetings": "Reuniones de hoy", "today.upcoming": "Próximos días", "today.upcomingEmpty": "Nada planificado para los próximos días.",
    "today.tasksCount_one": "1 tarea", "today.tasksCount_other": "{n} tareas", "today.meetingActions": "Acciones de reuniones",
    "today.recent": "Editado recientemente", "today.emptyTitle": "Empieza por aquí",
    "today.emptyText": "Añade tu primera tarea arriba, crea un proyecto o registra una reunión.",

    "inbox.subtitle": "Tareas sin fecha. Arrástralas a un día en la vista Semana cuando sepas cuándo hacerlas.",
    "inbox.addPh": "Apunta algo para no olvidarlo…", "inbox.empty": "Bandeja vacía. ✨",
    "inbox.tip": "Consejo: usa el menú ⋯ de cada tarea para planificarla en un día.",

    "week.word": "Semana", "week.prev": "Semana anterior", "week.next": "Semana siguiente", "week.thisWeek": "Esta semana",
    "week.progress": "{done} de {total} tareas hechas", "week.empty": "Semana sin tareas",
    "week.bringOverdue_one": "1 atrasada → hoy", "week.bringOverdue_other": "{n} atrasadas → hoy",
    "week.hideWeekend": "Ocultar fin de semana", "week.showWeekend": "Mostrar fin de semana",
    "week.hideInbox": "Ocultar columna Bandeja", "week.showInbox": "Mostrar columna Bandeja",
    "week.hint": "Arrastra las tareas para moverlas entre días o reordenarlas. Clic en el texto para editar.",

    "cal.prev": "Mes anterior", "cal.next": "Mes siguiente", "cal.more": "+{n} más", "cal.openWeek": "Ver semana",
    "cal.noMeetings": "Sin reuniones este día.", "cal.tasksTitle": "{open} pendientes de {total}",
    "cal.hint": "Clic en un día para ver su detalle · doble clic abre su semana · arrastra tareas del panel a otro día.",

    "task.add": "Añadir tarea", "task.addShort": "Añadir…", "task.markDone": "Marcar como hecha", "task.markUndone": "Marcar como pendiente",
    "task.edit": "Editar tarea", "task.editHint": "Enter guarda · Shift+Enter nueva línea (detalle) · Tab sangra · Esc cancela",
    "task.moveTo": "Mover a", "task.move": "Mover", "task.moved": "Tarea movida", "task.pickDate": "Elegir fecha…",
    "task.duplicate": "Duplicar", "task.openFile": "Abrir su archivo", "task.deleted": "Tarea eliminada", "task.clickText": "clic en el texto",

    "quick.title": "Nueva tarea", "quick.placeholder": "¿Qué hay que hacer?", "quick.add": "Añadir",
    "quick.hint": "Una tarea por línea. Añade #etiquetas o una hora al principio (10:30 …).",
    "quick.noProject": "Sin proyecto", "quick.added": "Tarea añadida", "quick.addedMany": "{n} tareas añadidas",

    "meeting.new": "Nueva reunión", "meeting.newOn": "Nueva reunión este día", "meeting.create": "Crear y tomar notas",
    "meeting.titlePh": "Ej. Seguimiento semanal con el equipo", "meeting.attendees": "Asistentes",
    "meeting.attendeesPh": "Ana, Luis, Marta", "meeting.attendeesHint": "Separados por comas", "meeting.now": "Ahora",
    "meeting.untitled": "Reunión", "meeting.openActions_one": "1 acción pendiente", "meeting.openActions_other": "{n} acciones pendientes",

    "meetings.subtitle_one": "1 reunión registrada", "meetings.subtitle_other": "{n} reuniones registradas",
    "meetings.searchPh": "Buscar por título, asistentes o contenido…", "meetings.allProjects": "Todos los proyectos",
    "meetings.noProject": "Sin proyecto", "meetings.upcoming": "Próximas", "meetings.undated": "Sin fecha",
    "meetings.noMatch": "Ninguna reunión coincide", "meetings.emptyTitle": "Aún no hay reuniones",
    "meetings.emptyText": "Registra tus reuniones para tener las notas, acuerdos y próximos pasos siempre a mano.",

    "note.new": "Nueva nota", "note.newDoc": "Nuevo documento", "note.create": "Crear nota", "note.titlePh": "Ej. Ideas para el trimestre",
    "note.projectHint": "Si eliges un proyecto, la nota se guarda dentro de su carpeta.", "note.pinLabel": "Fijar en el tablón",
    "note.pin": "Fijar en el tablón", "note.unpin": "Quitar del tablón", "note.untitled": "Nota",

    "notes.subtitle": "Notas generales: ideas, enlaces, planes… Las fijadas aparecen primero.", "notes.searchPh": "Buscar notas…",
    "notes.pinned": "Fijadas", "notes.others": "Otras notas", "notes.all": "Todas las notas",
    "notes.emptyTitle": "El tablón está vacío", "notes.emptyText": "Crea una nota para cualquier cosa que quieras tener a la vista.",

    "project.new": "Nuevo proyecto", "project.create": "Crear proyecto", "project.createFirst": "+ Crea tu primer proyecto",
    "project.namePh": "Ej. Migración a la nube", "project.descPh": "¿De qué va? (opcional)",
    "project.status.active": "Activos", "project.status.paused": "En pausa", "project.status.done": "Terminados",
    "project.statusLabel": "Estado", "project.markAs": "Marcar: {status}", "project.delete": "Eliminar proyecto",
    "project.deleteConfirm": "¿Eliminar «{name}» con todas sus reuniones y documentos? Irá a la papelera de la bóveda (.trash).",
    "project.deleted": "Proyecto eliminado", "project.notFound": "Proyecto no encontrado",
    "project.tab.overview": "Resumen", "project.tab.docs": "Documentos",
    "project.noMeetings": "Sin reuniones todavía.", "project.noDescription": "Sin descripción",
    "project.tasksHint": "Aquí aparecen las tareas con {tag} y las tareas pendientes dentro de los documentos del proyecto.",
    "project.planned": "Planificadas", "project.fromDocs": "En reuniones y documentos", "project.completed": "Completadas",
    "project.noPlanned": "Ninguna tarea planificada con esta etiqueta.", "project.noDocTasks": "Nada pendiente en los documentos.",
    "project.addTask": "Añadir tarea al proyecto", "project.noDocs": "Sin documentos",
    "project.noDocsText": "Guarda aquí especificaciones, decisiones, diagramas…",
    "project.emptyReadme": "Pulsa Editar para describir el proyecto: objetivo, contexto, enlaces…",
    "project.recentMeetings": "Últimas reuniones", "project.openTasks": "Tareas pendientes",

    "projects.subtitle_one": "1 proyecto activo", "projects.subtitle_other": "{n} proyectos activos",
    "projects.emptyTitle": "Sin proyectos", "projects.emptyText": "Agrupa reuniones, documentos y tareas por proyecto.",

    "doc.updated": "editado {when}", "doc.vault": "Bóveda", "doc.previous": "Anterior", "doc.next": "Siguiente",
    "doc.backlinks": "Enlazado desde", "doc.copyPath": "Copiar ruta del archivo", "doc.copyLink": "Copiar enlace [[…]]",
    "doc.deleteConfirm": "¿Eliminar «{name}»? Irá a la papelera de la bóveda (.trash).", "doc.deleted": "Eliminado",
    "doc.notFound": "Este archivo no existe (o se ha movido)", "doc.emptyBody": "Documento vacío. Pulsa para escribir.",

    "props.title": "Propiedades", "props.saved": "Guardado", "props.tagsPh": "idea, urgente",
    "props.moveHint": "Cambiar el proyecto mueve el archivo a su carpeta.",

    "editor.body": "Contenido", "editor.placeholder": "Escribe en Markdown… (# título, - lista, - [ ] tarea, [[enlace]])",
    "editor.saved": "Guardado", "editor.saving": "Guardando…", "editor.unsaved": "Sin guardar", "editor.error": "Error al guardar",
    "editor.conflict": "Conflicto", "editor.uploading": "Subiendo imagen…",
    "editor.conflictText": "Este archivo ha cambiado fuera del editor (otra app o un agente). ¿Qué versión quieres?",
    "editor.reload": "Usar la del disco", "editor.overwrite": "Mantener la mía", "editor.reloaded": "Actualizado con cambios externos",
    "editor.done": "Listo", "editor.previewEmpty": "La vista previa aparecerá aquí.",
    "editor.heading": "Título", "editor.bold": "Negrita", "editor.italic": "Cursiva", "editor.list": "Lista", "editor.task": "Tarea",
    "editor.quote": "Cita", "editor.link": "Enlace", "editor.linkText": "texto", "editor.wikilink": "Enlazar nota [[…]]",
    "editor.code": "Código", "editor.image": "Imagen", "editor.modeWrite": "Solo editor", "editor.modeSplit": "Editor + vista previa",
    "editor.modePreview": "Solo vista previa",
    "editor.help": "Se guarda automáticamente · Ctrl/⌘+Enter marca tarea · [[ enlaza notas · pega o arrastra imágenes · Esc para salir",

    "palette.placeholder": "Busca archivos, texto o comandos…", "palette.recent": "Recientes", "palette.commands": "Acciones",
    "palette.files": "Archivos", "palette.content": "En el contenido", "palette.createNote": "Crear nota «{q}»",

    "settings.title": "Ajustes", "settings.language": "Idioma", "settings.themeLabel": "Apariencia",
    "settings.theme.system": "Sistema", "settings.theme.light": "Claro", "settings.theme.dark": "Oscuro",
    "settings.weekend": "Mostrar sábado y domingo en la semana", "settings.inboxColumn": "Mostrar la Bandeja como columna en la semana",
    "settings.vault": "Bóveda", "settings.vaultHint": "Para usar otra carpeta, arranca Panel con --vault RUTA o edita panel.config.json.",
    "settings.shortcuts": "Atajos de teclado",

    "sc.palette": "Buscar / comandos", "sc.newTask": "Nueva tarea", "sc.newMeeting": "Nueva reunión", "sc.newNote": "Nueva nota",
    "sc.today": "Ir a Hoy", "sc.inbox": "Ir a Bandeja", "sc.week": "Ir a Semana", "sc.calendar": "Ir a Calendario",
    "sc.meetings": "Ir a Reuniones", "sc.notes": "Ir al Tablón", "sc.projects": "Ir a Proyectos",
    "sc.navigate": "Semana/mes anterior o siguiente", "sc.edit": "Editar el documento abierto", "sc.undo": "Deshacer el último cambio",
    "sc.save": "Guardar (editor)", "sc.toggleTask": "Marcar/desmarcar tarea (editor)", "sc.exitEditor": "Salir del editor",
    "sc.link": "Enlazar otra nota (editor)",

    "undo.add": "añadir tarea", "undo.toggle": "marcar tarea", "undo.edit": "editar", "undo.delete": "eliminar",
    "undo.move": "mover", "undo.create": "crear", "undo.done": "Deshecho: {what}", "undo.nothing": "Nada que deshacer",

    "tpl.notes": "Notas", "tpl.decisions": "Acuerdos", "tpl.next": "Próximos pasos", "tpl.goals": "Objetivos", "tpl.links": "Enlaces",

    "status.online": "Conectado al servidor local",
    "err.offline": "Sin conexión con el servidor local. ¿Está abierta la ventana de Panel?",
    "err.conflict": "El archivo cambió mientras se guardaba. Inténtalo de nuevo.",
    "err.taskGone": "Esa tarea ha cambiado en el archivo. Vista actualizada.",
    "err.render": "Algo ha fallado al mostrar esta pantalla",
    "err.noServer": "No se puede contactar con el servidor de Panel",
    "err.noServerHint": "Arranca Panel con el lanzador (panel.bat, panel.command o panel.sh) y recarga esta página.",

    "welcome.title": "Bienvenida a Panel", "welcome.lead": "Tareas, reuniones, proyectos y notas en una bóveda de archivos Markdown que es solo tuya.",
    "welcome.p1": "Todo se guarda como .md en tu disco: sin nube, sin cuentas", "welcome.p2": "Compatible con Obsidian, editores de texto y agentes de IA",
    "welcome.p3": "Funciona igual en Windows, macOS y Linux", "welcome.vaultAt": "Tu bóveda estará en",
    "welcome.create": "Crear bóveda nueva", "welcome.migrate": "Migrar mi bóveda anterior",
    "welcome.legacyTitle": "Se ha encontrado una bóveda de la versión anterior",
    "welcome.legacyText": "En {path}. Se copiará al nuevo formato; la original no se toca.",
    "welcome.migrated": "Migración completada: {n} archivos",
  },

  en: {
    "connect.demo": "Try it with sample data (nothing is saved)", "demo.title": "Demo mode", "demo.text": "Changes are not saved.", "demo.connect": "Use my vault",
    "err.offlineWeb": "Cannot reach your vault. Check your internet connection or the folder permission.", "err.backend": "Your vault cannot be opened",
    "storage.github": "GitHub repository", "storage.folder": "Folder on this computer", "storage.disconnect": "Disconnect",
    "storage.githubHelp": "Every change is a commit in your private repository: full history, and you can open it from any device. The token is only stored in this browser.",
    "storage.folderHelp": "Your files never leave this computer. Put the folder in OneDrive/Dropbox/iCloud to keep it in sync.",
    "storage.disconnectConfirm": "Panel will forget this vault in this browser (your files are not deleted). Continue?",
    "cal.webOnly": "The web version cannot read calendars (browsers block it for security). Use the desktop version to see your Outlook, Google or iCloud meetings automatically.",
    "upd.web": "The web version updates itself: you always have the latest one.",
    "connect.lead": "Tasks, meetings, projects and notes in Markdown files that are yours alone. Where do you want to keep them?",
    "connect.recommended": "Recommended", "connect.folderTitle": "A folder on this computer",
    "connect.folderText": "Your data never leaves your computer. Great for work. Put it in OneDrive or Dropbox to sync it.",
    "connect.folderUnsupported": "Your browser cannot open folders. Use Chrome, Edge or Brave on a computer, or choose GitHub / the desktop version.",
    "connect.folderBtn": "Choose folder", "connect.ghTitle": "A private GitHub repository",
    "connect.ghText": "In sync on all your devices, phone included, with the history of every change. Free.",
    "connect.ghBtn": "Connect GitHub", "connect.gh1": "Create an empty private repository.", "connect.gh1link": "Create repository →",
    "connect.gh2": "Create a token with “Contents: Read and write” for that repository only.", "connect.gh2link": "Create token →",
    "connect.gh3": "Paste the repository and the token here.", "connect.repo": "Repository", "connect.token": "Token",
    "connect.tokenHint": "Stored only in this browser and only sent to api.github.com.",
    "connect.ghConnect": "Connect", "connect.repoInvalid": "Write the repository as user/name", "connect.tokenMissing": "The token is missing",
    "connect.desktopTitle": "Desktop version", "connect.desktopText": "For Firefox or Safari, offline use, or to see your Outlook calendar automatically. Download, unzip, double-click.",
    "connect.privacy": "Panel has no servers and no accounts: the app runs in your browser and your data goes straight to your folder or your GitHub.",
    "connect.about": "Open source · GitHub", "connect.reopen": "Open “{name}”",
    "connect.reopenText": "For security, the browser asks every now and then for permission to open your folder again.", "connect.other": "Use another vault",
    "event.allDay": "All day", "event.takeNotes": "Create the notes for this meeting", "event.hint": "From your calendar · click to take notes",
    "settings.tab.general": "General", "settings.tab.calendar": "Calendar", "settings.tab.vault": "Vault", "settings.tab.updates": "Updates",
    "cal.settingsHelp": "Meetings from your calendar show up by themselves in Today, Week and Calendar. Click one to create its note (with title, time and attendees), placed in the day plan. Panel only reads your calendar, it never changes it.",
    "cal.outlook": "Outlook desktop", "cal.outlookHint": "reads the calendar of the classic Outlook app installed on this computer (Windows).",
    "cal.outlookOnlyWin": "only available on Windows with classic Outlook.",
    "cal.outlookAttendees": "Also read attendees (Outlook may ask for permission the first time)",
    "cal.icsLabel": ".ics calendars (one per line)", "cal.icsHint": "ICS link from Outlook on the web (Settings → Calendar → Shared calendars → Publish), Google Calendar (Secret address in iCal format), iCloud… or the path of an .ics file.",
    "cal.saveTest": "Save and test", "cal.testing": "Reading the calendar…", "cal.testResult_one": "Connected: 1 event in the next 2 weeks", "cal.testResult_other": "Connected: {n} events in the next 2 weeks",
    "vault.folder": "Vault folder", "vault.folderHint": "Put it in OneDrive, Dropbox, iCloud or Syncthing to keep it in sync across computers. If the new folder is empty, Panel will offer to create or migrate it.",
    "vault.change": "Use this folder", "vault.changeConfirm": "Panel will restart using “{path}”. Your current vault is not moved or deleted (move it there first if you want to keep it there). Continue?",
    "vault.changeOk": "Change and restart", "vault.restarting": "Restarting Panel with the new folder…",
    "vault.backupTitle": "Backups and export", "vault.backupHelp": "Export your whole vault as a .zip (to move it to another computer or keep it safe). Before every update Panel makes an automatic copy in the backups/ folder.",
    "vault.export": "Export vault (.zip)", "vault.backupNow": "Back up now", "vault.backupDone": "Backup saved to {path}",
    "vault.syncHelp": "To switch computers: install Panel, copy your vault folder (or unzip the .zip) and choose that folder here.",
    "upd.checking": "Checking for updates…", "upd.auto": "Check for updates on start", "upd.help": "Updates are downloaded from github.com/{repo}. Your data is never touched and the vault is backed up before updating.",
    "upd.available": "New version available: {v}", "upd.install": "Update to {v}", "upd.installShort": "Update", "upd.upToDate": "You have the latest version",
    "upd.title": "Update Panel", "upd.confirm": "Version {v} will be downloaded, your vault backed up into backups/ and Panel will restart by itself. Update now?",
    "upd.installing": "Downloading and installing the update…", "upd.restarting": "Restarting Panel…", "upd.banner": "Update to {v}", "upd.check": "Check for updates",
    "common.open": "Open", "cal.plan": "Day plan",
    "meeting.onlyDays": "Meetings can only be placed on a day", "meeting.rescheduled": "Meeting moved to {date}",
    "meeting.unplace": "Remove from the day plan", "meeting.unplaceHint": "keeps the meeting",
    "meeting.dragHint": "Drag the meeting between your tasks to order your day",
    "project.closedLink_one": "1 done or paused →", "project.closedLink_other": "{n} done or paused →",
    "tpl.title": "Templates", "tpl.label": "Template", "tpl.default": "Default", "tpl.builtin": "built-in", "tpl.edit": "Edit templates",
    "tpl.new": "new", "tpl.new.meeting": "New meeting template", "tpl.new.note": "New note template", "tpl.create": "Create template",
    "tpl.namePh": "e.g. Retro, 1:1, Interview…", "tpl.kind.meeting": "Meetings", "tpl.kind.note": "Notes",
    "tpl.editing": "Template · {name}",
    "tpl.help": "Templates are .md files in your vault's templates/ folder. meeting.md (or note.md) is the default one; add more and pick one when you create a meeting or note.",
    "tpl.placeholders": "Available variables: {{title}} · {{date}} · {{time}} · {{project}} · {{attendees}} · {{today}} · {{weekday}} · {{dateLong}}",
    "nav.today": "Today", "nav.inbox": "Inbox", "nav.week": "Week", "nav.calendar": "Calendar",
    "nav.meetings": "Meetings", "nav.notes": "Board", "nav.projects": "Projects", "nav.search": "Search",

    "common.cancel": "Cancel", "common.close": "Close", "common.color": "Colour", "common.confirm": "Confirm",
    "common.copied": "Copied", "common.date": "Date", "common.delete": "Delete", "common.description": "Description",
    "common.edit": "Edit", "common.more": "More options", "common.name": "Name", "common.noResults": "No results",
    "common.openFile": "Open the .md file", "common.project": "Project", "common.save": "Save", "common.seeAll": "See all",
    "common.tags": "Tags", "common.tasks": "Tasks", "common.time": "Time", "common.title": "Title", "common.undo": "Undo",

    "date.today": "Today", "date.tomorrow": "Tomorrow", "date.yesterday": "Yesterday", "date.nextWeek": "Next week",
    "time.now": "just now",

    "greet.morning": "Good morning", "greet.afternoon": "Good afternoon", "greet.evening": "Good evening", "greet.night": "Good night",

    "today.progress": "{done} of {total} tasks done", "today.nothing": "Nothing planned for today (yet)",
    "today.overdue": "Overdue", "today.bringAll": "Move all to today", "today.broughtAll_one": "1 task moved to today",
    "today.broughtAll_other": "{n} tasks moved to today", "today.tasks": "Today's plan", "today.addPh": "What do you need to do today?",
    "today.meetings": "Today's meetings", "today.upcoming": "Next days", "today.upcomingEmpty": "Nothing planned for the next days.",
    "today.tasksCount_one": "1 task", "today.tasksCount_other": "{n} tasks", "today.meetingActions": "Meeting actions",
    "today.recent": "Recently edited", "today.emptyTitle": "Start here",
    "today.emptyText": "Add your first task above, create a project or log a meeting.",

    "inbox.subtitle": "Tasks without a date. Drag them to a day in the Week view once you know when.",
    "inbox.addPh": "Jot something down so you don't forget…", "inbox.empty": "Inbox zero. ✨",
    "inbox.tip": "Tip: use each task's ⋯ menu to schedule it on a day.",

    "week.word": "Week", "week.prev": "Previous week", "week.next": "Next week", "week.thisWeek": "This week",
    "week.progress": "{done} of {total} tasks done", "week.empty": "No tasks this week",
    "week.bringOverdue_one": "1 overdue → today", "week.bringOverdue_other": "{n} overdue → today",
    "week.hideWeekend": "Hide weekend", "week.showWeekend": "Show weekend",
    "week.hideInbox": "Hide Inbox column", "week.showInbox": "Show Inbox column",
    "week.hint": "Drag tasks to move them between days or reorder them. Click the text to edit.",

    "cal.prev": "Previous month", "cal.next": "Next month", "cal.more": "+{n} more", "cal.openWeek": "Open week",
    "cal.noMeetings": "No meetings this day.", "cal.tasksTitle": "{open} open of {total}",
    "cal.hint": "Click a day for details · double-click opens its week · drag tasks from the panel onto another day.",

    "task.add": "Add task", "task.addShort": "Add…", "task.markDone": "Mark as done", "task.markUndone": "Mark as not done",
    "task.edit": "Edit task", "task.editHint": "Enter saves · Shift+Enter new line (details) · Tab indents · Esc cancels",
    "task.moveTo": "Move to", "task.move": "Move", "task.moved": "Task moved", "task.pickDate": "Pick a date…",
    "task.duplicate": "Duplicate", "task.openFile": "Open its file", "task.deleted": "Task deleted", "task.clickText": "click the text",

    "quick.title": "New task", "quick.placeholder": "What needs to be done?", "quick.add": "Add",
    "quick.hint": "One task per line. Add #tags or a leading time (10:30 …).",
    "quick.noProject": "No project", "quick.added": "Task added", "quick.addedMany": "{n} tasks added",

    "meeting.new": "New meeting", "meeting.newOn": "New meeting on this day", "meeting.create": "Create and take notes",
    "meeting.titlePh": "e.g. Weekly sync with the team", "meeting.attendees": "Attendees",
    "meeting.attendeesPh": "Ana, Luis, Marta", "meeting.attendeesHint": "Comma separated", "meeting.now": "Now",
    "meeting.untitled": "Meeting", "meeting.openActions_one": "1 open action", "meeting.openActions_other": "{n} open actions",

    "meetings.subtitle_one": "1 meeting logged", "meetings.subtitle_other": "{n} meetings logged",
    "meetings.searchPh": "Search by title, attendees or content…", "meetings.allProjects": "All projects",
    "meetings.noProject": "No project", "meetings.upcoming": "Upcoming", "meetings.undated": "No date",
    "meetings.noMatch": "No meeting matches", "meetings.emptyTitle": "No meetings yet",
    "meetings.emptyText": "Log your meetings to keep notes, decisions and next steps at hand.",

    "note.new": "New note", "note.newDoc": "New document", "note.create": "Create note", "note.titlePh": "e.g. Ideas for the quarter",
    "note.projectHint": "If you pick a project, the note is saved inside its folder.", "note.pinLabel": "Pin to the board",
    "note.pin": "Pin to the board", "note.unpin": "Unpin", "note.untitled": "Note",

    "notes.subtitle": "General notes: ideas, links, plans… Pinned ones come first.", "notes.searchPh": "Search notes…",
    "notes.pinned": "Pinned", "notes.others": "Other notes", "notes.all": "All notes",
    "notes.emptyTitle": "The board is empty", "notes.emptyText": "Create a note for anything you want to keep in sight.",

    "project.new": "New project", "project.create": "Create project", "project.createFirst": "+ Create your first project",
    "project.namePh": "e.g. Cloud migration", "project.descPh": "What is it about? (optional)",
    "project.status.active": "Active", "project.status.paused": "Paused", "project.status.done": "Done",
    "project.statusLabel": "Status", "project.markAs": "Mark as: {status}", "project.delete": "Delete project",
    "project.deleteConfirm": "Delete “{name}” with all its meetings and documents? It goes to the vault trash (.trash).",
    "project.deleted": "Project deleted", "project.notFound": "Project not found",
    "project.tab.overview": "Overview", "project.tab.docs": "Documents",
    "project.noMeetings": "No meetings yet.", "project.noDescription": "No description",
    "project.tasksHint": "Tasks tagged {tag} and open tasks inside the project's documents show up here.",
    "project.planned": "Planned", "project.fromDocs": "In meetings and documents", "project.completed": "Completed",
    "project.noPlanned": "No planned tasks with this tag.", "project.noDocTasks": "Nothing open in the documents.",
    "project.addTask": "Add a task to the project", "project.noDocs": "No documents",
    "project.noDocsText": "Keep specs, decisions, diagrams… here.",
    "project.emptyReadme": "Press Edit to describe the project: goal, context, links…",
    "project.recentMeetings": "Latest meetings", "project.openTasks": "Open tasks",

    "projects.subtitle_one": "1 active project", "projects.subtitle_other": "{n} active projects",
    "projects.emptyTitle": "No projects", "projects.emptyText": "Group meetings, documents and tasks by project.",

    "doc.updated": "edited {when}", "doc.vault": "Vault", "doc.previous": "Previous", "doc.next": "Next",
    "doc.backlinks": "Linked from", "doc.copyPath": "Copy file path", "doc.copyLink": "Copy [[…]] link",
    "doc.deleteConfirm": "Delete “{name}”? It goes to the vault trash (.trash).", "doc.deleted": "Deleted",
    "doc.notFound": "This file does not exist (or was moved)", "doc.emptyBody": "Empty document. Click to write.",

    "props.title": "Properties", "props.saved": "Saved", "props.tagsPh": "idea, urgent",
    "props.moveHint": "Changing the project moves the file into its folder.",

    "editor.body": "Content", "editor.placeholder": "Write Markdown… (# heading, - list, - [ ] task, [[link]])",
    "editor.saved": "Saved", "editor.saving": "Saving…", "editor.unsaved": "Unsaved", "editor.error": "Save failed",
    "editor.conflict": "Conflict", "editor.uploading": "Uploading image…",
    "editor.conflictText": "This file changed outside the editor (another app or an agent). Which version do you want?",
    "editor.reload": "Use the one on disk", "editor.overwrite": "Keep mine", "editor.reloaded": "Updated with external changes",
    "editor.done": "Done", "editor.previewEmpty": "The preview shows up here.",
    "editor.heading": "Heading", "editor.bold": "Bold", "editor.italic": "Italic", "editor.list": "List", "editor.task": "Task",
    "editor.quote": "Quote", "editor.link": "Link", "editor.linkText": "text", "editor.wikilink": "Link a note [[…]]",
    "editor.code": "Code", "editor.image": "Image", "editor.modeWrite": "Editor only", "editor.modeSplit": "Editor + preview",
    "editor.modePreview": "Preview only",
    "editor.help": "Saves automatically · Ctrl/⌘+Enter toggles a task · [[ links notes · paste or drop images · Esc to leave",

    "palette.placeholder": "Search files, text or commands…", "palette.recent": "Recent", "palette.commands": "Actions",
    "palette.files": "Files", "palette.content": "In content", "palette.createNote": "Create note “{q}”",

    "settings.title": "Settings", "settings.language": "Language", "settings.themeLabel": "Appearance",
    "settings.theme.system": "System", "settings.theme.light": "Light", "settings.theme.dark": "Dark",
    "settings.weekend": "Show Saturday and Sunday in the week", "settings.inboxColumn": "Show the Inbox as a column in the week",
    "settings.vault": "Vault", "settings.vaultHint": "To use another folder, start Panel with --vault PATH or edit panel.config.json.",
    "settings.shortcuts": "Keyboard shortcuts",

    "sc.palette": "Search / commands", "sc.newTask": "New task", "sc.newMeeting": "New meeting", "sc.newNote": "New note",
    "sc.today": "Go to Today", "sc.inbox": "Go to Inbox", "sc.week": "Go to Week", "sc.calendar": "Go to Calendar",
    "sc.meetings": "Go to Meetings", "sc.notes": "Go to Board", "sc.projects": "Go to Projects",
    "sc.navigate": "Previous / next week or month", "sc.edit": "Edit the open document", "sc.undo": "Undo the last change",
    "sc.save": "Save (editor)", "sc.toggleTask": "Toggle task (editor)", "sc.exitEditor": "Leave the editor",
    "sc.link": "Link another note (editor)",

    "undo.add": "add task", "undo.toggle": "check task", "undo.edit": "edit", "undo.delete": "delete",
    "undo.move": "move", "undo.create": "create", "undo.done": "Undone: {what}", "undo.nothing": "Nothing to undo",

    "tpl.notes": "Notes", "tpl.decisions": "Decisions", "tpl.next": "Next steps", "tpl.goals": "Goals", "tpl.links": "Links",

    "status.online": "Connected to the local server",
    "err.offline": "Cannot reach the local server. Is the Panel window still open?",
    "err.conflict": "The file changed while saving. Please try again.",
    "err.taskGone": "That task changed in the file. View refreshed.",
    "err.render": "Something went wrong showing this screen",
    "err.noServer": "Cannot reach the Panel server",
    "err.noServerHint": "Start Panel with its launcher (panel.bat, panel.command or panel.sh) and reload this page.",

    "welcome.title": "Welcome to Panel", "welcome.lead": "Tasks, meetings, projects and notes in a vault of Markdown files that is yours alone.",
    "welcome.p1": "Everything is saved as .md on your disk: no cloud, no accounts", "welcome.p2": "Works with Obsidian, text editors and AI agents",
    "welcome.p3": "Runs the same on Windows, macOS and Linux", "welcome.vaultAt": "Your vault will live in",
    "welcome.create": "Create a new vault", "welcome.migrate": "Migrate my previous vault",
    "welcome.legacyTitle": "A vault from the previous version was found",
    "welcome.legacyText": "At {path}. It will be copied into the new format; the original stays untouched.",
    "welcome.migrated": "Migration complete: {n} files",
  },
};
